<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWs5Y+45qaC5Ya1');
$cfg_Cs[2]=array(1,1,1,'SFRNTA==');
$cfg_Cs[3]=array(1,1,1,'RElWJkNTUw==');
$cfg_Cs[4]=array(1,1,1,'SmF2YXNjcmlwdC9BamF4');
$cfg_Cs[5]=array(1,1,1,'RHJlYW13ZWF2ZXI=');
$cfg_Cs[6]=array(0,2,1,'5YWs5Y+45Lqn5ZOB');
$cfg_Cs[7]=array(0,3,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[8]=array(0,6,1,'5Lq65omN5oub6IGY');
$cfg_Cs[9]=array(0,-8,1,'5paw5ZOB56CU5Y+R');
$cfg_Cs[10]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[11]=array(0,1,1,'5a6i5oi355WZ6KiA');
?>